version: '3.3'
#Structure inspired by: https://stackoverflow.com/questions/56643961/initialize-postgres-db-in-docker-compose
services:
  db:
    build: ./db
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dbs2021
    volumes:
      - ./data:/data
