version: '3.3'

services:
  db:
    build: ./db
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dbs2021
    volumes:
      - ./data:/data
